### ISSUE TITLE
How is the episode total cost tested during training?

### ISSUE THREAD

**Issue by Zarzard** [RL-boxes/Safe-RL#1]
Hello! I think CUP is a wonderful job but there are still some implementational details that confuse me.
It seems that there are no additional testing/evaluating stage during policy training? Is this [cost_ret_eps](https://github.com/RL-boxes/Safe-RL/blob/main/CUP/utils/data_generator.py#L84) used as the testing metric? If so, why is the cost discounted while the reward isn't?

**Comment by zmsn-2077** [comment]
Sorry for the late reply, according to the implementation of openai and realistic requirements, the cost should be without discount, but for the task of mujoco velocity, which first appeared in the article focops, the corresponding cost of this article is taken as a discount, so we have to take the discount for the sake of fairness of comparison.
For a non-discounted implementation, you can refer to this repository https://github.com/PKU-MARL/Safe-Policy-Optimization. We will migrate the CUP over in two weeks.
`focops:` https://github.com/ymzhang01/focops/blob/main/data_generator.py#L76
Your question makes a lot of sense and I don't know if my answer solved your doubts.

**Comment by Zarzard** [comment]
I see. BTW, have you ever tried forcing the episode length to be a fix number (so that you can use the trick in the [openai implementation](https://github.com/openai/safety-starter-agents/blob/master/safe_rl/sac/sac.py#L374))?

**Comment by zmsn-2077** [comment]
This we have not tried. QAQ.

**Comment by Zarzard** [comment]
OK, thanks for your answer.
